const jobsDatabase = [
    // SPHERE 1: IMMOBILIER & HABITAT
    { id: 'immo_agent', label: "Agent Immobilier", sphere: 'habitat', tags: ['vente', 'maison', 'appartement', 'mandat'] },
    { id: 'immo_architecte', label: "Architecte", sphere: 'habitat', tags: ['plan', 'construction', 'permis', 'design'] },
    { id: 'immo_maitre_oeuvre', label: "Maître d'œuvre", sphere: 'habitat', tags: ['chantier', 'coordination', 'travaux'] },
    { id: 'immo_courtier', label: "Courtier en Prêt", sphere: 'habitat', tags: ['financement', 'banque', 'crédit'] },
    { id: 'immo_notaire', label: "Notaire", sphere: 'habitat', tags: ['acte', 'juridique', 'vente'] },
    { id: 'immo_diagnostiqueur', label: "Diagnostiqueur", sphere: 'habitat', tags: ['dpe', 'amiante', 'audit'] },
    { id: 'immo_geometre', label: "Géomètre", sphere: 'habitat', tags: ['terrain', 'bornage', 'plan'] },
    { id: 'immo_gestionnaire', label: "Gestionnaire de Patrimoine", sphere: 'habitat', tags: ['investissement', 'fiscalité'] },
    { id: 'immo_chasseur', label: "Chasseur Immobilier", sphere: 'habitat', tags: ['recherche', 'achat'] },
    { id: 'immo_promoteur', label: "Promoteur Immobilier", sphere: 'habitat', tags: ['construction', 'neuf'] },
    { id: 'btp_electricien', label: "Électricien", sphere: 'habitat', tags: ['travaux', 'artisan', 'renovation'] },
    { id: 'btp_plombier', label: "Plombier", sphere: 'habitat', tags: ['travaux', 'artisan', 'sanitaire'] },
    { id: 'btp_peintre', label: "Peintre", sphere: 'habitat', tags: ['deco', 'artisan', 'finition'] },
    { id: 'btp_menuisier', label: "Menuisier", sphere: 'habitat', tags: ['bois', 'fenetre', 'cuisine'] },
    { id: 'btp_macon', label: "Maçon", sphere: 'habitat', tags: ['gros oeuvre', 'construction'] },
    { id: 'btp_paysagiste', label: "Paysagiste", sphere: 'habitat', tags: ['jardin', 'exterieur'] },
    { id: 'btp_pisciniste', label: "Pisciniste", sphere: 'habitat', tags: ['piscine', 'eau'] },
    { id: 'btp_cuisiniste', label: "Cuisiniste", sphere: 'habitat', tags: ['cuisine', 'amenagement'] },
    { id: 'btp_domotique', label: "Expert Domotique", sphere: 'habitat', tags: ['tech', 'maison', 'alarme'] },
    { id: 'immo_conciergerie', label: "Conciergerie Airbnb", sphere: 'habitat', tags: ['location', 'service'] },
    { id: 'immo_fengshui', label: "Expert Feng Shui", sphere: 'habitat', tags: ['bien-etre', 'deco', 'energie'] },
    { id: 'btp_floral', label: "Décorateur Floral", sphere: 'habitat', tags: ['fleurs', 'deco', 'evenement'] },

    // SPHERE 2: BUSINESS & DIGITAL (B2B)
    { id: 'biz_comptable', label: "Expert Comptable", sphere: 'business', tags: ['finance', 'bilan', 'entreprise'] },
    { id: 'biz_avocat_aff', label: "Avocat d'Affaires", sphere: 'business', tags: ['juridique', 'contrat', 'société'] },
    { id: 'biz_assureur_pro', label: "Assureur Pro", sphere: 'business', tags: ['risque', 'protection', 'rc pro'] },
    { id: 'biz_consultant_strat', label: "Consultant Stratégie", sphere: 'business', tags: ['conseil', 'direction'] },
    { id: 'biz_coach_biz', label: "Coach Business", sphere: 'business', tags: ['accompagnement', 'dirigeant'] },
    { id: 'biz_recruteur', label: "Recruteur / Chasseur de Tête", sphere: 'business', tags: ['rh', 'embauche'] },
    { id: 'biz_formateur', label: "Formateur", sphere: 'business', tags: ['pedagogie', 'competence'] },
    { id: 'biz_banquier_pro', label: "Banquier Pro", sphere: 'business', tags: ['compte', 'financement'] },
    { id: 'dig_webdesigner', label: "Webdesigner", sphere: 'business', tags: ['site', 'internet', 'visuel'] },
    { id: 'dig_dev_web', label: "Développeur Web", sphere: 'business', tags: ['code', 'app', 'site'] },
    { id: 'dig_seo', label: "Expert SEO", sphere: 'business', tags: ['google', 'referencement'] },
    { id: 'dig_ads', label: "Expert Publicité (Ads)", sphere: 'business', tags: ['pub', 'facebook', 'google'] },
    { id: 'dig_cm', label: "Community Manager", sphere: 'business', tags: ['reseaux sociaux', 'insta', 'linkedin'] },
    { id: 'dig_copywriter', label: "Copywriter", sphere: 'business', tags: ['ecriture', 'vente', 'email'] },
    { id: 'dig_graphiste', label: "Graphiste", sphere: 'business', tags: ['logo', 'print', 'identite'] },
    { id: 'dig_photographe_corp', label: "Photographe Corporate", sphere: 'business', tags: ['photo', 'portrait', 'produit'] },
    { id: 'dig_videaste', label: "Vidéaste", sphere: 'business', tags: ['video', 'montage', 'clip'] },
    { id: 'dig_cyber', label: "Expert Cybersécurité", sphere: 'business', tags: ['securite', 'informatique'] },
    { id: 'biz_imp', label: "Imprimeur", sphere: 'business', tags: ['print', 'flyer', 'carte'] },
    { id: 'dig_influenceur', label: "Influenceur Local", sphere: 'business', tags: ['reseaux sociaux', 'visibilite'] },
    { id: 'dig_podcast', label: "Expert Podcast", sphere: 'business', tags: ['audio', 'media', 'contenu'] },

    // SPHERE 3: BIEN-ÊTRE & SANTÉ
    { id: 'sante_osteo', label: "Ostéopathe", sphere: 'bien-etre', tags: ['soin', 'dos', 'sante'] },
    { id: 'sante_kine', label: "Kinésithérapeute", sphere: 'bien-etre', tags: ['reeducation', 'mouvement'] },
    { id: 'sante_coach_sport', label: "Coach Sportif", sphere: 'bien-etre', tags: ['sport', 'forme', 'physique'] },
    { id: 'sante_nutri', label: "Nutritionniste", sphere: 'bien-etre', tags: ['alimentation', 'regime'] },
    { id: 'sante_naturo', label: "Naturopathe", sphere: 'bien-etre', tags: ['naturel', 'plantes'] },
    { id: 'sante_sophro', label: "Sophrologue", sphere: 'bien-etre', tags: ['relaxation', 'stress'] },
    { id: 'sante_psy', label: "Psychologue", sphere: 'bien-etre', tags: ['mental', 'ecoute'] },
    { id: 'sante_hypno', label: "Hypnothérapeute", sphere: 'bien-etre', tags: ['inconscient', 'arret tabac'] },
    { id: 'sante_dentiste', label: "Dentiste", sphere: 'bien-etre', tags: ['dents', 'sourire'] },
    { id: 'be_coiffeur', label: "Coiffeur", sphere: 'bien-etre', tags: ['cheveux', 'beaute'] },
    { id: 'be_esthetique', label: "Esthéticienne", sphere: 'bien-etre', tags: ['soin', 'visage', 'corps'] },
    { id: 'be_spa', label: "Gérant de Spa", sphere: 'bien-etre', tags: ['detente', 'massage'] },
    { id: 'be_yoga', label: "Prof de Yoga", sphere: 'bien-etre', tags: ['souplesse', 'zen'] },
    { id: 'be_massage', label: "Masseur Bien-être", sphere: 'bien-etre', tags: ['massage', 'detente'] },
    { id: 'be_reflexo', label: "Réflexologue", sphere: 'bien-etre', tags: ['pieds', 'sante', 'naturel'] },
    { id: 'be_coach_vie', label: "Coach de Vie", sphere: 'bien-etre', tags: ['mental', 'objectif', 'perso'] },

    // SPHERE 4: COMMERCE & LOCAL
    { id: 'com_restaurateur', label: "Restaurateur", sphere: 'commerce', tags: ['repas', 'cuisine', 'accueil'] },
    { id: 'com_caviste', label: "Caviste", sphere: 'commerce', tags: ['vin', 'alcool', 'cadeau'] },
    { id: 'com_fleuriste', label: "Fleuriste", sphere: 'commerce', tags: ['fleurs', 'deco', 'mariage'] },
    { id: 'com_pret_a_porter', label: "Boutique Prêt-à-porter", sphere: 'commerce', tags: ['vetement', 'mode'] },
    { id: 'com_opticien', label: "Opticien", sphere: 'commerce', tags: ['lunettes', 'vue'] },
    { id: 'com_bijoutier', label: "Bijoutier", sphere: 'commerce', tags: ['bijoux', 'montre', 'luxe'] },
    { id: 'com_boulanger', label: "Boulanger / Pâtissier", sphere: 'commerce', tags: ['pain', 'gateau'] },
    { id: 'com_chocolatier', label: "Chocolatier", sphere: 'commerce', tags: ['chocolat', 'cadeau'] },
    { id: 'com_epicerie', label: "Épicerie Fine", sphere: 'commerce', tags: ['produit', 'gourmet'] },
    { id: 'com_libraire', label: "Libraire", sphere: 'commerce', tags: ['livre', 'culture'] },
    { id: 'com_hotel', label: "Hôtelier / Gîte", sphere: 'commerce', tags: ['nuit', 'tourisme'] },
    { id: 'com_traiteur', label: "Traiteur", sphere: 'commerce', tags: ['reception', 'mariage'] },
    { id: 'com_wedding', label: "Wedding Planner", sphere: 'commerce', tags: ['mariage', 'event'] },
    { id: 'com_event', label: "Organisateur Événementiel", sphere: 'commerce', tags: ['soiree', 'seminaire'] },
    { id: 'com_voyage', label: "Agent de Voyage", sphere: 'commerce', tags: ['vacances', 'billet'] },

    // SPHERE 5: CONSEIL & DROIT (Partially covered in Business but more specialized)
    { id: 'droit_avocat_famille', label: "Avocat Droit Famille", sphere: 'conseil', tags: ['divorce', 'famille'] },
    { id: 'droit_huissier', label: "Commissaire de Justice (Huissier)", sphere: 'conseil', tags: ['constat', 'recouvrement'] },
    { id: 'cons_rse', label: "Consultant RSE", sphere: 'conseil', tags: ['environnement', 'social'] },
    { id: 'cons_export', label: "Consultant Export", sphere: 'conseil', tags: ['international', 'douane'] },
    { id: 'cons_logistique', label: "Consultant Logistique", sphere: 'conseil', tags: ['supply chain', 'transport'] },
    { id: 'cons_mediateur', label: "Médiateur", sphere: 'conseil', tags: ['conflit', 'accord'] }
];
